[workspace]
members = [
    "protoc",
    "protoc-bin-vendored",
    # Exclude test-protoc from the project, because it depends on binary
    #"protoc/test-protoc",
    "protobuf",
    "protobuf-fuzz",
    "protobuf-codegen",
    "protobuf-codegen-pure-test",
    "protobuf-codegen-identical-test",
    "protobuf-examples/pure-vs-protoc",
    "protobuf-parse",
    "protobuf-test",
    "protobuf-test-common",
    "perftest/vs-cxx",
    "perftest/bytes",
    "perftest/misc",
    "ci-gen",
]
