on:
    - push
    - pull_request
name: CI
jobs:
    linux-stable-default-features:
        name: linux stable (default features)
        runs-on: ubuntu-latest
        env:
            RUST_BACKTRACE: 1
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: Cache protobuf
              uses: actions/cache@v2
              with:
                  key: pb-linux-3.19.4
                  path: ~/pb
              env:
                  cache-name: pb
            - name: Install protobuf
              run: ci/install-protobuf.sh
              shell: bash
              env:
                  PROTOBUF_VERSION: 3.19.4
            - name: Protoc check
              run: protoc --version
              shell: bash
            - name: Compile interop
              run: test-crates/interop/cxx/compile.sh
              shell: bash
            - name: Regenerate
              run: protobuf/regenerate.sh
              shell: bash
            - name: Test all
              run: cargo test --all --all-targets
              shell: bash
            - name: Test all
              run: cargo test
              shell: bash
            - name: cargo doc
              uses: actions-rs/cargo@v1
              with:
                  command: doc
    linux-stable-with-bytes:
        name: linux stable (with-bytes)
        runs-on: ubuntu-latest
        env:
            RUST_BACKTRACE: 1
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: Cache protobuf
              uses: actions/cache@v2
              with:
                  key: pb-linux-3.19.4
                  path: ~/pb
              env:
                  cache-name: pb
            - name: Install protobuf
              run: ci/install-protobuf.sh
              shell: bash
              env:
                  PROTOBUF_VERSION: 3.19.4
            - name: Protoc check
              run: protoc --version
              shell: bash
            - name: Compile interop
              run: test-crates/interop/cxx/compile.sh
              shell: bash
            - name: protobuf-codegen-protoc-test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --manifest-path=test-crates/protobuf-codegen-protoc-test/Cargo.toml --features=with-bytes
            - name: protobuf-codegen-pure-test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --manifest-path=test-crates/protobuf-codegen-pure-test/Cargo.toml --features=with-bytes
    rustfmt-check:
        name: rustfmt check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Cache protobuf
              uses: actions/cache@v2
              with:
                  key: pb-linux-3.19.4
                  path: ~/pb
              env:
                  cache-name: pb
            - name: Install protobuf
              run: ci/install-protobuf.sh
              shell: bash
              env:
                  PROTOBUF_VERSION: 3.19.4
            - name: Protoc check
              run: protoc --version
              shell: bash
            - name: cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check
            - name: cargo fmt check
              run: cargo fmt -- --check
              shell: bash
